/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9fd",
        "secondary-fixed-dim": "#ffb3af",
        "surface-tint": "#28638a",
        "on-error": "#ffffff",
        "on-surface-variant": "#41474e",
        "surface-variant": "#e1e2e6",
        "primary-fixed-dim": "#96ccf9",
        "on-secondary-fixed-variant": "#8b1820",
        "background": "#f8f9fd",
        "outline": "#71787f",
        "surface-container-high": "#e7e8ec",
        "on-tertiary": "#ffffff",
        "text-secondary": "#666666",
        "on-primary-fixed": "#001e30",
        "surface-bright": "#f8f9fd",
        "inverse-primary": "#96ccf9",
        "secondary": "#ac3134",
        "primary-container": "#266289",
        "surface-container-highest": "#e1e2e6",
        "secondary-container": "#fd6d6b",
        "on-secondary-container": "#6d000f",
        "tertiary-fixed": "#ffddb2",
        "tertiary-container": "#7e550d",
        "on-background": "#191c1f",
        "tertiary": "#613f00",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f7",
        "surface-container": "#edeef1",
        "on-surface": "#191c1f",
        "tertiary-fixed-dim": "#f4bd6e",
        "overlay-black": "rgba(0,0,0,0.9)",
        "on-primary-fixed-variant": "#004b71",
        "on-primary-container": "#b2dbff",
        "on-tertiary-fixed": "#291800",
        "surface-dark": "#1c1c1c",
        "secondary-fixed": "#ffdad7",
        "inverse-surface": "#2e3133",
        "on-tertiary-fixed-variant": "#624000",
        "primary": "#004a6f",
        "on-tertiary-container": "#ffcf8c",
        "on-secondary-fixed": "#410005",
        "on-error-container": "#93000a",
        "primary-fixed": "#cbe6ff",
        "inverse-on-surface": "#f0f1f4",
        "surface-dim": "#d9dadd",
        "error-container": "#ffdad6",
        "surface-footer": "#252525",
        "error": "#ba1a1a",
        "text-primary": "#767676",
        "outline-variant": "#c1c7cf",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "15px",
        "hero-height": "300px",
        "gutter": "30px",
        "container-max": "1170px",
        "section-padding-bottom": "80px",
        "section-padding-top": "83px"
      },
      fontFamily: {
        "title-lg": ["Source Sans 3", "sans-serif"],
        "headline-sm": ["Source Sans 3", "sans-serif"],
        "headline-xl": ["Source Sans 3", "sans-serif"],
        "headline-lg-mobile": ["Source Sans 3", "sans-serif"],
        "headline-lg": ["Source Sans 3", "sans-serif"],
        "headline-md": ["Source Sans 3", "sans-serif"],
        "body-lg": ["Raleway", "sans-serif"],
        "body-md": ["Raleway", "sans-serif"],
        "headline-xl-mobile": ["Source Sans 3", "sans-serif"],
        "label-md": ["Source Sans 3", "sans-serif"]
      },
      fontSize: {
        "title-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-sm": ["25px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-xl": ["52px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg": ["42px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl-mobile": ["36px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }]
      },
      animation: {
        'fade-in': 'fadeIn 1s ease-out forwards',
        'fade-in-right': 'fadeInRight 1s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        }
      }
    },
  },
  plugins: [],
}
